### ISSUE TITLE
Review / Refactor

### ISSUE THREAD

**Issue by adamstallard** [UnitapApp/unitap-pass#1]
https://github.com/UnitapApp/unitap-pass/blob/f85cb085a84298c1c509a1cec36937d555b54fa4/contracts/UnitapPass.sol#L32-L46

Why are you overriding these two functions if you're only calling the parent function? These two overrides seem to do nothing.

**Comment by adamstallard** [comment]
https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L7-L11

https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L21

Creating a struct and an array of batches adds unneeded complexity. We only work with one batch at a time (the current one).

We can have `batchSize` `soldCount` and `price` as global variables.

**Comment by adamstallard** [comment]
https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L19

https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L66

We don't need to store or compute the total value sold in the contract.  We are tracking the number sold, and we should not change the price (see my comment https://github.com/UnitapApp/unitap-pass/issues/2#issuecomment-1336543686)

**Comment by 0xoc** [comment]
> https://github.com/UnitapApp/unitap-pass/blob/f85cb085a84298c1c509a1cec36937d555b54fa4/contracts/UnitapPass.sol#L32-L46
> 
> Why are you overriding these two functions if you're only calling the parent function? These two overrides seem to do nothing.

Since the two functions are defined in both classes (ERC721, ERC721URIStorage) the code would not compile without these overrides.

**Comment by 0xoc** [comment]
> https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L76-L79
> 
> https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L21
> 
> Creating a struct and an array of batches adds unneeded complexity. We only work with one batch at a time (the current one).
> 
> We can have `batchSize` `soldCount` and `price` as global variables.

Yes, since there is only one active batch at a time, we could only keep global variables. However, history-keeping is much easier this way; accessing historical data (eg. how many were sold in a specific batch) requires off-chain scripting. If this is not a concern, I can remove the struct and the array.

**Comment by adamstallard** [comment]
> > https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L76-L79
> > https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L21
> > Creating a struct and an array of batches adds unneeded complexity. We only work with one batch at a time (the current one).
> > We can have `batchSize` `soldCount` and `price` as global variables.
> 
> Yes, since there is only one active batch at a time, we could only keep global variables. However, history-keeping is much easier this way; accessing historical data (eg. how many were sold in a specific batch) requires off-chain scripting. If this is not a concern, I can remove the struct and the array.

If we store an array, it increases gas due to increased storage (probably not an issue) and complicates the code (which is an issue: simpler code is easier to audit).  Please remove the struct and array.

Accessing historical data about how many were sold in a specific batch can be done easily off-chain using Events.  It looks like you already have the events needed to do this (`StartBatch`) and (`MultiMint`).  They could be changed to not include a batch number, which can be easily inferred by looking at the order of events.

Making our frontend able to read events is preferable to adding any extra code to smart contracts.  Frontends are easy to change and fix; smart contracts are ideally never changed.

**Comment by adamstallard** [comment]
One thing you probably already realize @spsina , but I'll point it out just in case:

Since we're not storing batches in an array anymore we don't need to check if a batch is ended before starting a new one: https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L42-L44 

In fact, I think we should remove this check, because otherwise there is no way to end a batch sale.  Without the check, we can end a batch sale by starting a new sale with a batch size of 0.  We could then restart it by starting a new sale with a batch size > 0.

**Comment by adamstallard** [comment]
@spsina I want to make sure that there's no way that this number can wrap around if there's an overflow.  https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L38

Could the contract mint more than the MAX if a batch was created with a very high number causing the integer to wrap around past zero, or would it just cause an overflow error and revert?

Also here https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L53

Could someone mint more than allowed by requesting a huge number that wraps around, or will it revert?

It seems like even if it did wrap around, they'd have to request a huge number that they wouldn't be able to pay for, so it will revert.

EDIT: It looks like since solidity 0.8 , overflow checks for arithmetic are built in:  https://docs.soliditylang.org/en/latest/080-breaking-changes.html

> Arithmetic operations revert on underflow and overflow

https://stackoverflow.com/questions/70074736/do-you-need-safemath-in-solidity-version-0-8-and-if-not-can-you-still-import

We used to use the "SafeMath" library for everything.
This confirms that we no longer need it in solidity 0.8 +
