### ISSUE TITLE
Make the contract immune to theft of ETH or NFTs even if the owner is compromised

### ISSUE THREAD

**Issue by adamstallard** [UnitapApp/unitap-pass#2]
https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L76-L79

Instead of making a function that allows the owner to withdraw ETH to any address, we can set the safe address in the constructor and make it unchangeable.  Then the withdraw function can be called by anyone, and will transfer the eth in the contract to the safe address.

I think the withdraw function should always withdraw all ETH, unless you can think of a reason to prefer to keep ETH in the contract instead of in the safe.  (I can't.)

**Comment by adamstallard** [comment]
Let's set the price in the constructor and make it unchangeable.

If we set the price in the constructor and make it unchangeable, then even if the contract owner is compromised, all an attacker can do is sell NFTs up to the allowed maximum, or stop the sale.  They can't do any damage before we remove the minter role from this contract and deploy a new contract.

If we allow the price to be changed, then an attacker could steal all the NFTs up to the maximum amount by setting the price to 0.

If we need to change the price in the future (which is not planned), we can deploy a new contract and set a different price in the constructor and give it the minter role.

**Comment by 0xoc** [comment]
> https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L76-L79
> 
> Instead of making a function that allows the owner to withdraw ETH to any address, we can set the safe address in the constructor and make it unchangeable. Then the withdraw function can be called by anyone, and will transfer the eth in the contract to the safe address.
> 
> I think the withdraw function should always withdraw all ETH, unless you can think of a reason to prefer to keep ETH in the contract instead of in the safe. (I can't.)

If we make the safe address a global variable, and all ETH can ever go to this address (which is a safer approach in our case), then we don't need to have the amount or the address as an argument to the withdrawETH function.
But in the case of the owner being able to withdraw ETH to any address, it would make sense to have an amount; not because you'd want to keep eth in the contract but because you don't want to withdraw it all to a specific address.

**Comment by adamstallard** [comment]
> > https://github.com/UnitapApp/unitap-pass/blob/main/contracts/UnitapPassBatchSale.sol#L76-L79
> > Instead of making a function that allows the owner to withdraw ETH to any address, we can set the safe address in the constructor and make it unchangeable. Then the withdraw function can be called by anyone, and will transfer the eth in the contract to the safe address.
> > I think the withdraw function should always withdraw all ETH, unless you can think of a reason to prefer to keep ETH in the contract instead of in the safe. (I can't.)
> 
> If we make the safe address a global variable, and all ETH can ever go to this address (which is a safer approach in our case), then we don't need to have the amount or the address as an argument to the withdrawETH function. But in the case of the owner being able to withdraw ETH to any address, it would make sense to have an amount; not because you'd want to keep eth in the contract but because you don't want to withdraw it all to a specific address.

Right, so let's simplify by not allowing the address or amount to be set, and not requiring the caller to be the owner.
